# Generated by Django 5.1 on 2025-05-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on_feed', models.BooleanField(default=False, verbose_name='Отображать на главной странице?')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('short_title', models.CharField(max_length=150, verbose_name='Короткий заголовок')),
                ('description', models.TextField(max_length=12000, verbose_name='Полное описание')),
                ('short_description', models.TextField(max_length=1200, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='article_images/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('vk_link', models.CharField(max_length=100, verbose_name='Ссылка на VK')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=100, verbose_name='Заголовок на баннере')),
                ('hero_link', models.CharField(max_length=100, verbose_name='Ссылка с баннера')),
                ('joining_step_1_title', models.CharField(max_length=100, verbose_name='Шаг 1 — заголовок')),
                ('joining_step_1_description', models.CharField(max_length=100, verbose_name='Шаг 1 — описание')),
                ('joining_step_2_title', models.CharField(max_length=100, verbose_name='Шаг 2 — заголовок')),
                ('joining_step_2_description', models.CharField(max_length=100, verbose_name='Шаг 2 — описание')),
                ('joining_step_3_title', models.CharField(max_length=100, verbose_name='Шаг 3 — заголовок')),
                ('joining_step_3_description', models.CharField(max_length=100, verbose_name='Шаг 3 — описание')),
                ('joining_step_4_title', models.CharField(max_length=100, verbose_name='Шаг 4 — заголовок')),
                ('joining_step_4_description', models.CharField(max_length=100, verbose_name='Шаг 4 — описание')),
                ('right_image', models.ImageField(upload_to='main_page/right_image', verbose_name='Изображение справа')),
            ],
        ),
    ]
