# Generated by Django 5.1 on 2025-05-26 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_contacts_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
