# Generated by Django 5.2.1 on 2025-06-17 17:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_gallery_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория достижения',
                'verbose_name_plural': 'Категории достижений',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='short_title',
            field=models.CharField(default='...', max_length=150, verbose_name='Короткий заголовок'),
        ),
        migrations.CreateModel(
            name='Achievment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('short_title', models.CharField(max_length=150, verbose_name='Короткий заголовок')),
                ('description', models.TextField(max_length=12000, verbose_name='Полное описание')),
                ('short_description', models.TextField(max_length=1200, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='article_images/', verbose_name='Изображение')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.achievmentcategory')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
    ]
