# Generated by Django 5.2.1 on 2025-06-17 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_socialpsychologyservice_socialpsychologyservicelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=12000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Дополнительное образование',
                'verbose_name_plural': 'Дополнительное образование',
            },
        ),
        migrations.CreateModel(
            name='AdditionalEducationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ссылки')),
                ('url', models.URLField(verbose_name='URL ссылки')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pages.additionaleducation', verbose_name='Орган управления')),
            ],
            options={
                'verbose_name': 'Ссылка для дополнительного образования',
                'verbose_name_plural': 'Ссылки для дополнительного образования',
            },
        ),
    ]
