# Generated by Django 5.2.1 on 2025-06-17 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_additionaleducation_additionaleducationlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=12000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сведения об образовательной организации',
                'verbose_name_plural': 'Сведения об образовательной организации',
            },
        ),
        migrations.AlterField(
            model_name='additionaleducationlink',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pages.additionaleducation', verbose_name='Дополнительное образование'),
        ),
        migrations.AlterField(
            model_name='socialpsychologyservicelink',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pages.socialpsychologyservice', verbose_name='Социально-психологическая служба'),
        ),
        migrations.CreateModel(
            name='AdditionalOrganizationParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=12000, verbose_name='Описание')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='pages.additionalorganization', verbose_name='Сведения об образовательной организации')),
            ],
            options={
                'verbose_name': 'Абзац в сведениях об образовательной организации',
                'verbose_name_plural': 'Абзац в сведениях об образовательной организации',
            },
        ),
    ]
