# Generated by Django 5.2.1 on 2025-06-18 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_additionalorganization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInformationMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school_information/', verbose_name='Изображение на баннере')),
                ('hero_title', models.CharField(max_length=500, verbose_name='Заголовок на баннере')),
            ],
            options={
                'verbose_name': 'Информация о школе: Главная',
                'verbose_name_plural': 'Информация о школе: Главная',
            },
        ),
        migrations.CreateModel(
            name='SchoolInformationMainItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school_information/', verbose_name='Изображение')),
                ('subtitle', models.CharField(max_length=1000, verbose_name='Надзаголовок')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст')),
                ('link_text', models.CharField(max_length=1000, verbose_name='Текст ссылки')),
                ('link_url', models.URLField(max_length=1000, verbose_name='Ссылка')),
                ('school_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.schoolinformationmain')),
            ],
            options={
                'verbose_name': 'Элемент главной страницы',
                'verbose_name_plural': 'Элемент главной страницы',
            },
        ),
        migrations.DeleteModel(
            name='AdditionalOrganizationParagraph',
        ),
    ]
