# Generated by Django 5.2.1 on 2025-06-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_schoolinformationmain_schoolinformationmainitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinformationmainitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='school_information/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='schoolinformationmainitem',
            name='link_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст ссылки'),
        ),
        migrations.AlterField(
            model_name='schoolinformationmainitem',
            name='link_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='schoolinformationmainitem',
            name='subtitle',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Надзаголовок'),
        ),
        migrations.AlterField(
            model_name='schoolinformationmainitem',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='schoolinformationmainitem',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок'),
        ),
    ]
