# Generated by Django 5.2.1 on 2025-06-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_schoolinformationmainitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinformationmain',
            name='hero_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок на баннере'),
        ),
    ]
