# Generated by Django 5.2.1 on 2025-06-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_schoolinformationmain_hero_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInformationDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1000, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Информация о школе: Реквизиты для поддержки',
                'verbose_name_plural': 'Информация о школе: Реквизиты для поддержки',
            },
        ),
        migrations.CreateModel(
            name='SchoolInformationHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Информация о школе: Помощь от учеников',
                'verbose_name_plural': 'Информация о школе: Помощь от учеников',
            },
        ),
        migrations.CreateModel(
            name='SchoolInformationHelpItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer', models.IntegerField(verbose_name='Число статистики')),
                ('subtitle', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст статистики')),
            ],
            options={
                'verbose_name': 'Элемент статистики',
                'verbose_name_plural': 'Элемент статистики',
            },
        ),
    ]
