# Generated by Django 5.2.1 on 2025-06-18 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_schoolinformationdonation_schoolinformationhelp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinformationhelpitem',
            name='school_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.schoolinformationhelp'),
        ),
    ]
