# Generated by Django 5.2.1 on 2025-06-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_schoolinformationhelpitem_school_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInformationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок блока с изображением')),
                ('subtitle', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Подзаголовок блока с изображением')),
                ('should_add_support', models.BooleanField(default=False, verbose_name='Добавить блок "Поддержка школы"')),
                ('content', models.TextField(max_length=50000, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Информация о школе: Дополнительные страницы',
                'verbose_name_plural': 'Информация о школе: Дополнительные страницы',
            },
        ),
    ]
