# Generated by Django 5.2.1 on 2025-06-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_schoolinformationpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinformationpage',
            name='page_title',
            field=models.CharField(default='...', max_length=1000, verbose_name='Название страницы'),
        ),
    ]
