# Generated by Django 5.2.1 on 2025-06-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_schoolinformationpage_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinformationpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='school_information/', verbose_name='Изображение'),
        ),
    ]
