# Generated by Django 5.2.1 on 2025-06-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_schoolinformationpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinformationpage',
            name='custom_breadcrumbs',
            field=models.CharField(blank=True, null=True, verbose_name='Указать "хлебные крошки"'),
        ),
    ]
