# Generated by Django 5.2.1 on 2025-06-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_schoolinformationpage_custom_breadcrumbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryOfSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school_information/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=1000, verbose_name='Подзаголовок')),
                ('content', models.TextField(max_length=50000, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Информация о школе: История Казанской церкви',
                'verbose_name_plural': 'Информация о школе: История Казанской церкви',
            },
        ),
        migrations.CreateModel(
            name='WebsiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название изображения')),
                ('image', models.ImageField(upload_to='all_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Загрузка изображения',
                'verbose_name_plural': 'Загрузка изображений',
            },
        ),
    ]
