# Generated by Django 5.2.1 on 2025-06-24 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_historyofschool_websiteimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppendAlgoritm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school_information/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Информация о школе: Алгоритм поступления',
                'verbose_name_plural': 'Информация о школе: Алгоритм поступления',
            },
        ),
        migrations.CreateModel(
            name='AppendAlgoritmStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст')),
                ('algoritm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pages.appendalgoritm', verbose_name='Шаги')),
            ],
            options={
                'verbose_name': 'Шаг алгоритма поступления',
                'verbose_name_plural': 'Шаги алгоритма поступления',
            },
        ),
    ]
