# Generated by Django 5.2.1 on 2025-06-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_appendalgoritm_appendalgoritmstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appendalgoritmstep',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст'),
        ),
    ]
