# Generated by Django 5.2.1 on 2025-06-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_appendalgoritmstep_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInformationHelpMini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='school_information/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Помощь школе: Мини-блок',
                'verbose_name_plural': 'Помощь школе: Мини-блок',
            },
        ),
    ]
