# Generated by Django 5.2.1 on 2025-06-24 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_schoolinformationhelpmini'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school_information/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=1000, verbose_name='Подзаголовок')),
                ('content', models.TextField(max_length=50000, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Питание',
                'verbose_name_plural': 'Питания',
            },
        ),
        migrations.CreateModel(
            name='CuisineRegime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('text', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regime', to='pages.cuisine', verbose_name='Режим питания')),
            ],
            options={
                'verbose_name': 'Режим питания',
                'verbose_name_plural': 'Режим питания',
            },
        ),
    ]
