# Generated by Django 5.2.1 on 2025-06-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_vacancy_vacancytag'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL ссылки'),
        ),
    ]
