# Generated by Django 5.2.1 on 2025-06-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_vacancy_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BellSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='Начало')),
                ('time_end', models.TimeField(verbose_name='Конец')),
                ('text', models.CharField(max_length=300, verbose_name='Описание')),
                ('break_after', models.PositiveIntegerField(blank=True, null=True, verbose_name='Будет ли перемена? Если да, то укажите ее продолжительность')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность(опционально)')),
            ],
            options={
                'verbose_name': 'Расписание звонков и автобусов',
                'verbose_name_plural': 'Расписание звонков и автобусов',
            },
        ),
    ]
