# Generated by Django 5.2.1 on 2025-06-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_bellschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='bellschedule',
            name='is_red',
            field=models.BooleanField(default=False, verbose_name='Сделать описание красного цвета?'),
        ),
    ]
