# Generated by Django 5.2.1 on 2025-06-25 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_bellschedule_is_red'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000, verbose_name='Название маршрута')),
                ('image', models.ImageField(upload_to='maps/', verbose_name='Вариант 1: Изображение с картой')),
                ('iframe', models.TextField(max_length=10000, verbose_name='Вариант 2: Ссылка на яндекс карту')),
            ],
            options={
                'verbose_name': 'Расписание автобусов',
                'verbose_name_plural': 'Расписание автобусов',
            },
        ),
        migrations.AlterModelOptions(
            name='bellschedule',
            options={'verbose_name': 'Расписание звонков', 'verbose_name_plural': 'Расписание звонков'},
        ),
        migrations.CreateModel(
            name='BusScheduleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('text', models.CharField(max_length=300, verbose_name='Описание')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='pages.busschedule')),
            ],
            options={
                'verbose_name': 'Время расписания автобусов',
                'verbose_name_plural': 'Время расписания автобусов',
            },
        ),
    ]
