# Generated by Django 5.2.1 on 2025-06-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_busschedule_alter_bellschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='iframe',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Вариант 2: Ссылка на яндекс карту'),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maps/', verbose_name='Вариант 1: Изображение с картой'),
        ),
    ]
