# Generated by Django 5.2.1 on 2025-06-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_alter_busschedule_iframe_alter_busschedule_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busscheduletime',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='busscheduletime',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
    ]
