# Generated by Django 5.2.1 on 2025-06-26 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_alter_busscheduletime_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=12000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Государственная итоговая аттестация',
                'verbose_name_plural': 'Государственная итоговая аттестация',
            },
        ),
        migrations.CreateModel(
            name='AttestationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=2000, verbose_name='Название')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL ссылки')),
                ('attestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pages.attestation')),
            ],
            options={
                'verbose_name': 'Ссылка на странице',
                'verbose_name_plural': 'Ссылки на странице',
            },
        ),
    ]
