# Generated by Django 5.2.1 on 2025-06-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_attestation_attestationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attestation/', verbose_name='Изображение'),
        ),
    ]
