# Generated by Django 5.2.1 on 2025-06-26 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_attestation_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPageA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=2000, verbose_name='Название страницы')),
            ],
            options={
                'verbose_name': "Шаблон страницы типа 'А'",
                'verbose_name_plural': "Страницы типа 'А'",
            },
        ),
        migrations.CreateModel(
            name='GenericPageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория в навигации',
                'verbose_name_plural': 'Категории в навигации',
            },
        ),
        migrations.CreateModel(
            name='GenericPageA_Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=20000, verbose_name='Описание')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='pages.genericpagea')),
            ],
            options={
                'verbose_name': 'Абзац',
                'verbose_name_plural': 'Абзацы',
            },
        ),
        migrations.CreateModel(
            name='GenericPageB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=2000, verbose_name='Название страницы')),
                ('description', models.TextField(max_length=20000, verbose_name='Описание')),
                ('title_color', models.CharField(choices=[('#913232', 'Красный'), ('#4F5F4D', 'Зелёный')], default='#913232', max_length=7, verbose_name='Цвет заголовка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages_b', to='pages.genericpagecategory')),
            ],
            options={
                'verbose_name': "Шаблон страницы типа 'Б'",
                'verbose_name_plural': "Страницы типа 'Б'",
            },
        ),
        migrations.AddField(
            model_name='genericpagea',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages_a', to='pages.genericpagecategory'),
        ),
    ]
