# Generated by Django 5.2.1 on 2025-06-26 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_genericpagea_genericpagecategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericpagea',
            options={'verbose_name': "Страница типа 'А'", 'verbose_name_plural': "Страницы типа 'А'"},
        ),
        migrations.AlterModelOptions(
            name='genericpageb',
            options={'verbose_name': "Страница типа 'Б'", 'verbose_name_plural': "Страницы типа 'Б'"},
        ),
        migrations.AddField(
            model_name='genericpagea',
            name='path',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Путь к странице'),
        ),
        migrations.AddField(
            model_name='genericpageb',
            name='path',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Путь к странице'),
        ),
        migrations.AlterField(
            model_name='genericpagea',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages_a', to='pages.genericpagecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='genericpageb',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages_b', to='pages.genericpagecategory', verbose_name='Категория'),
        ),
    ]
