# Generated by Django 5.2.1 on 2025-06-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_alter_genericpagea_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, verbose_name='Название')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет предмета')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL ссылки')),
                ('description', models.TextField(max_length=20000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Предметная неделя',
                'verbose_name_plural': 'Предметные недели',
            },
        ),
    ]
