# Generated by Django 5.2.1 on 2025-06-26 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_subjectweek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectweek',
            name='url',
        ),
    ]
