# Generated by Django 5.2.1 on 2025-06-28 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_remove_subjectweek_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Свободные места: Школа',
                'verbose_name_plural': 'Свободные места: Школы',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег учителя',
                'verbose_name_plural': 'Теги учителей',
            },
        ),
        migrations.CreateModel(
            name='GradeNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер класса')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='pages.grade', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Свободные места: Класс',
                'verbose_name_plural': 'Свободные места: Классы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('education', models.CharField(max_length=1000, verbose_name='Образование')),
                ('direction', models.CharField(max_length=1000, verbose_name='Направление подготовки ')),
                ('degree', models.CharField(max_length=1000, verbose_name='Ученая степень ')),
                ('experience', models.CharField(max_length=1000, verbose_name='Стаж работы ')),
                ('tags', models.ManyToManyField(related_name='teachers', to='pages.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='GradeFullness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parallel', models.CharField(max_length=100, verbose_name='Параллель')),
                ('is_full', models.BooleanField(default=False, verbose_name='Есть ли свободные места?')),
                ('grade_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='pages.gradenumber', verbose_name='Класс')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='pages.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Свободные места',
                'verbose_name_plural': 'Свободные места',
            },
        ),
    ]
