# Generated by Django 5.2.1 on 2025-06-28 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_grade_tag_gradenumber_teacher_gradefullness'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория учителя',
                'verbose_name_plural': 'Категории учителей',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='pages.teachercategory', verbose_name='Категория'),
        ),
    ]
