# Generated by Django 5.2.1 on 2025-06-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_teachercategory_teacher_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Фото'),
        ),
    ]
