# Generated by Django 5.2.1 on 2025-06-28 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_alter_gradefullness_grade_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradefullness',
            name='grade_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='pages.gradenumber', verbose_name='Класс'),
        ),
    ]
