# Generated by Django 5.2.1 on 2025-06-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_alter_gradefullness_grade_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinformationmainitem',
            name='link_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка'),
        ),
    ]
