# Generated by Django 5.2.1 on 2025-06-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0046_alter_schoolinformationmainitem_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpagea',
            name='show_in_nav',
            field=models.BooleanField(default=False, verbose_name='Показать страницу в навигации?'),
        ),
        migrations.AddField(
            model_name='genericpageb',
            name='show_in_nav',
            field=models.BooleanField(default=False, verbose_name='Показать страницу в навигации?'),
        ),
    ]
