# Generated by Django 5.2.1 on 2025-07-02 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_genericpagea_show_in_nav_genericpageb_show_in_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpageb',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_b', to='pages.genericpagecategory', verbose_name='Категория'),
        ),
    ]
