# Generated by Django 5.2.1 on 2025-07-02 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_alter_genericpageb_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpagecategory',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на страницу'),
        ),
        migrations.AlterField(
            model_name='genericpagea',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_a', to='pages.genericpagecategory', verbose_name='Категория'),
        ),
    ]
