# Generated by Django 5.2.1 on 2025-07-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_genericpagecategory_link_alter_genericpagea_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationitem',
            name='url',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
