# Generated by Django 5.2.1 on 2025-07-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0050_alter_attestationitem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='hero_link',
        ),
    ]
