# Generated by Django 5.2.1 on 2025-07-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0051_remove_mainpage_hero_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appendalgoritm',
            options={'verbose_name': 'Алгоритм поступления', 'verbose_name_plural': 'Алгоритм поступления'},
        ),
        migrations.RemoveField(
            model_name='busschedule',
            name='iframe',
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maps/', verbose_name='Изображение с картой'),
        ),
    ]
